# Generated by Django 4.2.5 on 2024-07-14 13:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('backendAPI', '0003_contactform_faq_alter_product_filters_partners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('solved', 'Résolu'), ('en-attente', 'En Attente')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('memory bandwidth', 'Memory Bandwidth - GPU'), ('cooling support', 'Cooling Support - Case'), ('motherboard support', 'Motherboard Support - Case'), ('write speed', 'Write Speed - Storage'), ('memory size', 'Memory Size - GPU'), ('wifi', 'WiFi - Motherboard'), ('type', 'Type - Cooler'), ('dimensions', 'Dimensions - Power Supply'), ('wattage', 'Wattage - Power Supply'), ('drive bays', 'Drive Bays - Case'), ('pcie slots', 'PCIe Slots - Motherboard'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('warranty', 'Warranty - Power Supply'), ('lan', 'LAN - Motherboard'), ('fan size', 'Fan Size - Cooler'), ('chipset', 'Chipset - Motherboard'), ('voltage', 'Voltage - RAM'), ('powerConsumption', 'Power Consumption - CPU'), ('support', 'Support - Motherboard'), ('type', 'Type - RAM'), ('size', 'Size - Monitor'), ('speed', 'Speed - RAM'), ('form factor', 'Form Factor - Motherboard'), ('eco_mode', 'Eco Mode - Power Supply'), ('form factor', 'Form Factor - Power Supply'), ('airflow', 'Airflow - Cooler'), ('directx support', 'DirectX Support - GPU'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('architecture', 'Architecture - CPU'), ('panel type', 'Panel Type - Monitor'), ('dimensions', 'Dimensions - RAM'), ('expansion slots', 'Expansion Slots - Case'), ('capacity', 'Capacity - Storage'), ('powerConsumption', 'Power Consumption - Cooler'), ('latency', 'Latency - RAM'), ('socket', 'Socket - Motherboard'), ('form factor', 'Form Factor - Case'), ('heat spreader', 'Heat Spreader - RAM'), ('length', 'Length - GPU'), ('dimensions', 'Dimensions - Cooler'), ('powerConsumption', 'Power Consumption - Motherboard'), ('cache', 'Cache - CPU'), ('dimensions', 'Dimensions - Case'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('certifications', 'Certifications - Power Supply'), ('max psu length', 'Max PSU Length - Case'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('fan size', 'Fan Size - Power Supply'), ('front panel ports', 'Front Panel Ports - Case'), ('radiator_size', 'Radiator Size - Cooler'), ('memory speed', 'Memory Speed - Motherboard'), ('memory type', 'Memory Type - GPU'), ('response time', 'Response Time - Monitor'), ('capacity', 'Capacity - RAM'), ('powerConsumption', 'Power Consumption - GPU'), ('max memory', 'Max Memory - Motherboard'), ('controller', 'Controller - Storage'), ('socket', 'Socket - CPU'), ('rgb', 'RGB - RAM'), ('modules', 'Modules - RAM'), ('ports', 'Ports - GPU'), ('form factor', 'Form Factor - Storage'), ('memory slots', 'Memory Slots - Motherboard'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('sata ports', 'SATA Ports - Motherboard'), ('bearing type', 'Bearing Type - Cooler'), ('type', 'Type - Storage'), ('rgb', 'RGB - Cooler'), ('noise level', 'Noise Level - Cooler'), ('refresh rate', 'Refresh Rate - Monitor'), ('cores', 'Cores - CPU'), ('read speed', 'Read Speed - Storage'), ('tdp', 'TDP - CPU'), ('usb ports', 'USB Ports - Motherboard'), ('modularity', 'Modularity - Power Supply'), ('memory interface', 'Memory Interface - GPU'), ('chipset', 'Chipset - GPU'), ('fan', 'Fan - Power Supply'), ('interface', 'Interface - Storage'), ('resolution', 'Resolution - Monitor'), ('stream_processors', 'Stream Processors - GPU'), ('max gpu length', 'Max GPU Length - Case'), ('max cpu height', 'Max CPU Height - Case'), ('connectivity', 'Connectivity - Monitor'), ('threads', 'Threads - CPU'), ('cuda cores', 'CUDA Cores - GPU'), ('chipset', 'Chipset - CPU'), ('type', 'Type - Motherboard')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='ProductPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='backendAPI.product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='backendAPI.ProductPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
