# Generated by Django 4.2.5 on 2024-07-14 13:25

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0004_alter_contactform_state_alter_product_filters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('en-attente', 'En Attente'), ('solved', 'Résolu')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('tdp', 'TDP - CPU'), ('memory speed', 'Memory Speed - Motherboard'), ('form factor', 'Form Factor - Case'), ('front panel ports', 'Front Panel Ports - Case'), ('type', 'Type - Storage'), ('voltage', 'Voltage - RAM'), ('lan', 'LAN - Motherboard'), ('response time', 'Response Time - Monitor'), ('wattage', 'Wattage - Power Supply'), ('refresh rate', 'Refresh Rate - Monitor'), ('powerConsumption', 'Power Consumption - Cooler'), ('rgb', 'RGB - RAM'), ('certifications', 'Certifications - Power Supply'), ('drive bays', 'Drive Bays - Case'), ('heat spreader', 'Heat Spreader - RAM'), ('dimensions', 'Dimensions - Case'), ('memory size', 'Memory Size - GPU'), ('form factor', 'Form Factor - Motherboard'), ('type', 'Type - RAM'), ('airflow', 'Airflow - Cooler'), ('latency', 'Latency - RAM'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('radiator_size', 'Radiator Size - Cooler'), ('sata ports', 'SATA Ports - Motherboard'), ('cores', 'Cores - CPU'), ('memory interface', 'Memory Interface - GPU'), ('controller', 'Controller - Storage'), ('resolution', 'Resolution - Monitor'), ('connectivity', 'Connectivity - Monitor'), ('dimensions', 'Dimensions - RAM'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('dimensions', 'Dimensions - Cooler'), ('memory slots', 'Memory Slots - Motherboard'), ('size', 'Size - Monitor'), ('motherboard support', 'Motherboard Support - Case'), ('stream_processors', 'Stream Processors - GPU'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('fan size', 'Fan Size - Power Supply'), ('rgb', 'RGB - Cooler'), ('panel type', 'Panel Type - Monitor'), ('capacity', 'Capacity - Storage'), ('form factor', 'Form Factor - Storage'), ('expansion slots', 'Expansion Slots - Case'), ('warranty', 'Warranty - Power Supply'), ('architecture', 'Architecture - CPU'), ('type', 'Type - Motherboard'), ('form factor', 'Form Factor - Power Supply'), ('socket', 'Socket - CPU'), ('write speed', 'Write Speed - Storage'), ('type', 'Type - Cooler'), ('chipset', 'Chipset - GPU'), ('dimensions', 'Dimensions - Power Supply'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('noise level', 'Noise Level - Cooler'), ('threads', 'Threads - CPU'), ('modularity', 'Modularity - Power Supply'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('pcie slots', 'PCIe Slots - Motherboard'), ('memory type', 'Memory Type - GPU'), ('speed', 'Speed - RAM'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('socket', 'Socket - Motherboard'), ('support', 'Support - Motherboard'), ('fan', 'Fan - Power Supply'), ('modules', 'Modules - RAM'), ('max cpu height', 'Max CPU Height - Case'), ('powerConsumption', 'Power Consumption - Motherboard'), ('eco_mode', 'Eco Mode - Power Supply'), ('powerConsumption', 'Power Consumption - CPU'), ('max memory', 'Max Memory - Motherboard'), ('wifi', 'WiFi - Motherboard'), ('capacity', 'Capacity - RAM'), ('usb ports', 'USB Ports - Motherboard'), ('chipset', 'Chipset - CPU'), ('cache', 'Cache - CPU'), ('bearing type', 'Bearing Type - Cooler'), ('length', 'Length - GPU'), ('fan size', 'Fan Size - Cooler'), ('ports', 'Ports - GPU'), ('interface', 'Interface - Storage'), ('powerConsumption', 'Power Consumption - GPU'), ('cuda cores', 'CUDA Cores - GPU'), ('read speed', 'Read Speed - Storage'), ('max gpu length', 'Max GPU Length - Case'), ('chipset', 'Chipset - Motherboard'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('directx support', 'DirectX Support - GPU'), ('max psu length', 'Max PSU Length - Case'), ('cooling support', 'Cooling Support - Case')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
