# Generated by Django 4.2.5 on 2024-07-15 15:46

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0007_alter_contactform_state_alter_product_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='header_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('en-attente', 'En Attente'), ('solved', 'Résolu')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=wagtail.fields.StreamField([('Product_Section', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('big_headline', wagtail.blocks.TextBlock(blank=True)), ('header', wagtail.blocks.TextBlock(blank=True)), ('caption', wagtail.blocks.TextBlock(blank=True))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('powerConsumption', 'Power Consumption - GPU'), ('dimensions', 'Dimensions - Case'), ('pcie slots', 'PCIe Slots - Motherboard'), ('fan', 'Fan - Power Supply'), ('powerConsumption', 'Power Consumption - Cooler'), ('chipset', 'Chipset - CPU'), ('modularity', 'Modularity - Power Supply'), ('cooling support', 'Cooling Support - Case'), ('drive bays', 'Drive Bays - Case'), ('certifications', 'Certifications - Power Supply'), ('refresh rate', 'Refresh Rate - Monitor'), ('motherboard support', 'Motherboard Support - Case'), ('cuda cores', 'CUDA Cores - GPU'), ('socket', 'Socket - Motherboard'), ('max gpu length', 'Max GPU Length - Case'), ('form factor', 'Form Factor - Case'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('memory interface', 'Memory Interface - GPU'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('fan size', 'Fan Size - Power Supply'), ('wattage', 'Wattage - Power Supply'), ('directx support', 'DirectX Support - GPU'), ('stream_processors', 'Stream Processors - GPU'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('panel type', 'Panel Type - Monitor'), ('chipset', 'Chipset - GPU'), ('airflow', 'Airflow - Cooler'), ('memory type', 'Memory Type - GPU'), ('warranty', 'Warranty - Power Supply'), ('cache', 'Cache - CPU'), ('dimensions', 'Dimensions - Power Supply'), ('controller', 'Controller - Storage'), ('type', 'Type - Motherboard'), ('type', 'Type - Storage'), ('rgb', 'RGB - Cooler'), ('connectivity', 'Connectivity - Monitor'), ('expansion slots', 'Expansion Slots - Case'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('size', 'Size - Monitor'), ('usb ports', 'USB Ports - Motherboard'), ('fan size', 'Fan Size - Cooler'), ('wifi', 'WiFi - Motherboard'), ('max memory', 'Max Memory - Motherboard'), ('radiator_size', 'Radiator Size - Cooler'), ('length', 'Length - GPU'), ('ports', 'Ports - GPU'), ('modules', 'Modules - RAM'), ('front panel ports', 'Front Panel Ports - Case'), ('cores', 'Cores - CPU'), ('heat spreader', 'Heat Spreader - RAM'), ('interface', 'Interface - Storage'), ('rgb', 'RGB - RAM'), ('sata ports', 'SATA Ports - Motherboard'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('capacity', 'Capacity - Storage'), ('architecture', 'Architecture - CPU'), ('eco_mode', 'Eco Mode - Power Supply'), ('lan', 'LAN - Motherboard'), ('latency', 'Latency - RAM'), ('memory slots', 'Memory Slots - Motherboard'), ('dimensions', 'Dimensions - Cooler'), ('dimensions', 'Dimensions - RAM'), ('speed', 'Speed - RAM'), ('socket', 'Socket - CPU'), ('write speed', 'Write Speed - Storage'), ('type', 'Type - Cooler'), ('noise level', 'Noise Level - Cooler'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('bearing type', 'Bearing Type - Cooler'), ('max psu length', 'Max PSU Length - Case'), ('powerConsumption', 'Power Consumption - Motherboard'), ('voltage', 'Voltage - RAM'), ('response time', 'Response Time - Monitor'), ('capacity', 'Capacity - RAM'), ('tdp', 'TDP - CPU'), ('support', 'Support - Motherboard'), ('form factor', 'Form Factor - Motherboard'), ('read speed', 'Read Speed - Storage'), ('chipset', 'Chipset - Motherboard'), ('memory speed', 'Memory Speed - Motherboard'), ('resolution', 'Resolution - Monitor'), ('threads', 'Threads - CPU'), ('form factor', 'Form Factor - Storage'), ('form factor', 'Form Factor - Power Supply'), ('type', 'Type - RAM'), ('memory size', 'Memory Size - GPU'), ('max cpu height', 'Max CPU Height - Case'), ('powerConsumption', 'Power Consumption - CPU')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
