# Generated by Django 4.2.14 on 2024-07-17 10:50

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0008_product_header_description_alter_contactform_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('solved', 'Résolu'), ('en-attente', 'En Attente')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('pcie slots', 'PCIe Slots - Motherboard'), ('certifications', 'Certifications - Power Supply'), ('directx support', 'DirectX Support - GPU'), ('radiator_size', 'Radiator Size - Cooler'), ('capacity', 'Capacity - RAM'), ('connectivity', 'Connectivity - Monitor'), ('warranty', 'Warranty - Power Supply'), ('heat spreader', 'Heat Spreader - RAM'), ('memory type', 'Memory Type - GPU'), ('motherboard support', 'Motherboard Support - Case'), ('length', 'Length - GPU'), ('powerConsumption', 'Power Consumption - GPU'), ('fan size', 'Fan Size - Power Supply'), ('form factor', 'Form Factor - Storage'), ('max cpu height', 'Max CPU Height - Case'), ('memory interface', 'Memory Interface - GPU'), ('memory size', 'Memory Size - GPU'), ('front panel ports', 'Front Panel Ports - Case'), ('type', 'Type - RAM'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('form factor', 'Form Factor - Case'), ('usb ports', 'USB Ports - Motherboard'), ('cores', 'Cores - CPU'), ('type', 'Type - Storage'), ('write speed', 'Write Speed - Storage'), ('wattage', 'Wattage - Power Supply'), ('wifi', 'WiFi - Motherboard'), ('speed', 'Speed - RAM'), ('dimensions', 'Dimensions - RAM'), ('memory slots', 'Memory Slots - Motherboard'), ('cuda cores', 'CUDA Cores - GPU'), ('response time', 'Response Time - Monitor'), ('resolution', 'Resolution - Monitor'), ('noise level', 'Noise Level - Cooler'), ('form factor', 'Form Factor - Motherboard'), ('interface', 'Interface - Storage'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('dimensions', 'Dimensions - Cooler'), ('capacity', 'Capacity - Storage'), ('threads', 'Threads - CPU'), ('max gpu length', 'Max GPU Length - Case'), ('tdp', 'TDP - CPU'), ('eco_mode', 'Eco Mode - Power Supply'), ('dimensions', 'Dimensions - Case'), ('chipset', 'Chipset - GPU'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('type', 'Type - Cooler'), ('modularity', 'Modularity - Power Supply'), ('fan', 'Fan - Power Supply'), ('modules', 'Modules - RAM'), ('form factor', 'Form Factor - Power Supply'), ('dimensions', 'Dimensions - Power Supply'), ('socket', 'Socket - Motherboard'), ('chipset', 'Chipset - CPU'), ('architecture', 'Architecture - CPU'), ('latency', 'Latency - RAM'), ('bearing type', 'Bearing Type - Cooler'), ('voltage', 'Voltage - RAM'), ('cache', 'Cache - CPU'), ('cooling support', 'Cooling Support - Case'), ('rgb', 'RGB - Cooler'), ('powerConsumption', 'Power Consumption - Motherboard'), ('stream_processors', 'Stream Processors - GPU'), ('max psu length', 'Max PSU Length - Case'), ('socket', 'Socket - CPU'), ('ports', 'Ports - GPU'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('lan', 'LAN - Motherboard'), ('controller', 'Controller - Storage'), ('fan size', 'Fan Size - Cooler'), ('powerConsumption', 'Power Consumption - CPU'), ('drive bays', 'Drive Bays - Case'), ('expansion slots', 'Expansion Slots - Case'), ('rgb', 'RGB - RAM'), ('chipset', 'Chipset - Motherboard'), ('type', 'Type - Motherboard'), ('refresh rate', 'Refresh Rate - Monitor'), ('memory speed', 'Memory Speed - Motherboard'), ('airflow', 'Airflow - Cooler'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('sata ports', 'SATA Ports - Motherboard'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('powerConsumption', 'Power Consumption - Cooler'), ('read speed', 'Read Speed - Storage'), ('size', 'Size - Monitor'), ('max memory', 'Max Memory - Motherboard'), ('panel type', 'Panel Type - Monitor'), ('support', 'Support - Motherboard')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
