# Generated by Django 4.2.14 on 2024-07-17 13:30

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0010_alter_product_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.IntegerField(max_length=200, null=True)),
                ('facebook', models.TextField()),
                ('instagram', models.TextField()),
                ('tiktok', models.TextField()),
                ('youtube', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('fan size', 'Fan Size - Power Supply'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('dimensions', 'Dimensions - Cooler'), ('motherboard support', 'Motherboard Support - Case'), ('modularity', 'Modularity - Power Supply'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('sata ports', 'SATA Ports - Motherboard'), ('threads', 'Threads - CPU'), ('socket', 'Socket - CPU'), ('powerConsumption', 'Power Consumption - Cooler'), ('write speed', 'Write Speed - Storage'), ('type', 'Type - Storage'), ('rgb', 'RGB - RAM'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('pcie slots', 'PCIe Slots - Motherboard'), ('airflow', 'Airflow - Cooler'), ('cooling support', 'Cooling Support - Case'), ('ports', 'Ports - GPU'), ('max memory', 'Max Memory - Motherboard'), ('interface', 'Interface - Storage'), ('directx support', 'DirectX Support - GPU'), ('speed', 'Speed - RAM'), ('rgb', 'RGB - Cooler'), ('form factor', 'Form Factor - Motherboard'), ('memory speed', 'Memory Speed - Motherboard'), ('fan size', 'Fan Size - Cooler'), ('support', 'Support - Motherboard'), ('tdp', 'TDP - CPU'), ('architecture', 'Architecture - CPU'), ('front panel ports', 'Front Panel Ports - Case'), ('socket', 'Socket - Motherboard'), ('form factor', 'Form Factor - Case'), ('resolution', 'Resolution - Monitor'), ('memory interface', 'Memory Interface - GPU'), ('form factor', 'Form Factor - Power Supply'), ('drive bays', 'Drive Bays - Case'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('powerConsumption', 'Power Consumption - CPU'), ('controller', 'Controller - Storage'), ('noise level', 'Noise Level - Cooler'), ('memory type', 'Memory Type - GPU'), ('refresh rate', 'Refresh Rate - Monitor'), ('warranty', 'Warranty - Power Supply'), ('max psu length', 'Max PSU Length - Case'), ('heat spreader', 'Heat Spreader - RAM'), ('type', 'Type - RAM'), ('modules', 'Modules - RAM'), ('fan', 'Fan - Power Supply'), ('type', 'Type - Cooler'), ('dimensions', 'Dimensions - Case'), ('cache', 'Cache - CPU'), ('max gpu length', 'Max GPU Length - Case'), ('length', 'Length - GPU'), ('form factor', 'Form Factor - Storage'), ('chipset', 'Chipset - GPU'), ('max cpu height', 'Max CPU Height - Case'), ('response time', 'Response Time - Monitor'), ('bearing type', 'Bearing Type - Cooler'), ('capacity', 'Capacity - Storage'), ('dimensions', 'Dimensions - Power Supply'), ('radiator_size', 'Radiator Size - Cooler'), ('wattage', 'Wattage - Power Supply'), ('chipset', 'Chipset - CPU'), ('capacity', 'Capacity - RAM'), ('cuda cores', 'CUDA Cores - GPU'), ('lan', 'LAN - Motherboard'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('stream_processors', 'Stream Processors - GPU'), ('type', 'Type - Motherboard'), ('dimensions', 'Dimensions - RAM'), ('expansion slots', 'Expansion Slots - Case'), ('size', 'Size - Monitor'), ('powerConsumption', 'Power Consumption - Motherboard'), ('connectivity', 'Connectivity - Monitor'), ('eco_mode', 'Eco Mode - Power Supply'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('usb ports', 'USB Ports - Motherboard'), ('powerConsumption', 'Power Consumption - GPU'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('memory size', 'Memory Size - GPU'), ('latency', 'Latency - RAM'), ('voltage', 'Voltage - RAM'), ('read speed', 'Read Speed - Storage'), ('certifications', 'Certifications - Power Supply'), ('memory slots', 'Memory Slots - Motherboard'), ('panel type', 'Panel Type - Monitor'), ('chipset', 'Chipset - Motherboard'), ('cores', 'Cores - CPU'), ('wifi', 'WiFi - Motherboard')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
