# Generated by Django 4.2.14 on 2024-07-18 10:20

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0011_affiliation_alter_product_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('wilaya', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('en-attente', 'En Attente'), ('solved', 'Résolu')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('cooling support', 'Cooling Support - Case'), ('modularity', 'Modularity - Power Supply'), ('read speed', 'Read Speed - Storage'), ('controller', 'Controller - Storage'), ('bearing type', 'Bearing Type - Cooler'), ('capacity', 'Capacity - RAM'), ('directx support', 'DirectX Support - GPU'), ('write speed', 'Write Speed - Storage'), ('heat spreader', 'Heat Spreader - RAM'), ('panel type', 'Panel Type - Monitor'), ('max gpu length', 'Max GPU Length - Case'), ('sata ports', 'SATA Ports - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('front panel ports', 'Front Panel Ports - Case'), ('memory type', 'Memory Type - GPU'), ('warranty', 'Warranty - Power Supply'), ('connectivity', 'Connectivity - Monitor'), ('expansion slots', 'Expansion Slots - Case'), ('ports', 'Ports - GPU'), ('refresh rate', 'Refresh Rate - Monitor'), ('max cpu height', 'Max CPU Height - Case'), ('powerConsumption', 'Power Consumption - Motherboard'), ('voltage', 'Voltage - RAM'), ('threads', 'Threads - CPU'), ('latency', 'Latency - RAM'), ('memory speed', 'Memory Speed - Motherboard'), ('speed', 'Speed - RAM'), ('rgb', 'RGB - RAM'), ('memory slots', 'Memory Slots - Motherboard'), ('powerConsumption', 'Power Consumption - GPU'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('pcie slots', 'PCIe Slots - Motherboard'), ('cuda cores', 'CUDA Cores - GPU'), ('chipset', 'Chipset - GPU'), ('usb ports', 'USB Ports - Motherboard'), ('type', 'Type - Cooler'), ('dimensions', 'Dimensions - Power Supply'), ('length', 'Length - GPU'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('motherboard support', 'Motherboard Support - Case'), ('type', 'Type - Motherboard'), ('capacity', 'Capacity - Storage'), ('memory size', 'Memory Size - GPU'), ('fan size', 'Fan Size - Cooler'), ('lan', 'LAN - Motherboard'), ('modules', 'Modules - RAM'), ('type', 'Type - Storage'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('powerConsumption', 'Power Consumption - CPU'), ('memory interface', 'Memory Interface - GPU'), ('form factor', 'Form Factor - Storage'), ('response time', 'Response Time - Monitor'), ('tdp', 'TDP - CPU'), ('wifi', 'WiFi - Motherboard'), ('cache', 'Cache - CPU'), ('airflow', 'Airflow - Cooler'), ('form factor', 'Form Factor - Motherboard'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('fan', 'Fan - Power Supply'), ('socket', 'Socket - Motherboard'), ('support', 'Support - Motherboard'), ('chipset', 'Chipset - Motherboard'), ('dimensions', 'Dimensions - Case'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('chipset', 'Chipset - CPU'), ('eco_mode', 'Eco Mode - Power Supply'), ('max psu length', 'Max PSU Length - Case'), ('resolution', 'Resolution - Monitor'), ('drive bays', 'Drive Bays - Case'), ('cores', 'Cores - CPU'), ('dimensions', 'Dimensions - Cooler'), ('wattage', 'Wattage - Power Supply'), ('certifications', 'Certifications - Power Supply'), ('size', 'Size - Monitor'), ('architecture', 'Architecture - CPU'), ('socket', 'Socket - CPU'), ('max memory', 'Max Memory - Motherboard'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('rgb', 'RGB - Cooler'), ('type', 'Type - RAM'), ('powerConsumption', 'Power Consumption - Cooler'), ('noise level', 'Noise Level - Cooler'), ('stream_processors', 'Stream Processors - GPU'), ('form factor', 'Form Factor - Case'), ('dimensions', 'Dimensions - RAM'), ('form factor', 'Form Factor - Power Supply'), ('interface', 'Interface - Storage'), ('radiator_size', 'Radiator Size - Cooler')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
