# Generated by Django 4.2.14 on 2024-07-18 12:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0012_checkoutinfo_alter_contactform_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinfo',
            name='dispatch',
            field=models.CharField(default='FromStore', max_length=200),
        ),
        migrations.AddField(
            model_name='checkoutinfo',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backendAPI.product'),
        ),
        migrations.AddField(
            model_name='checkoutinfo',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('solved', 'Résolu'), ('en-attente', 'En Attente')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('usb ports', 'USB Ports - Motherboard'), ('form factor', 'Form Factor - Storage'), ('lan', 'LAN - Motherboard'), ('radiator_size', 'Radiator Size - Cooler'), ('type', 'Type - RAM'), ('rgb', 'RGB - Cooler'), ('front panel ports', 'Front Panel Ports - Case'), ('chipset', 'Chipset - CPU'), ('heat spreader', 'Heat Spreader - RAM'), ('powerConsumption', 'Power Consumption - GPU'), ('modules', 'Modules - RAM'), ('panel type', 'Panel Type - Monitor'), ('max gpu length', 'Max GPU Length - Case'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('support', 'Support - Motherboard'), ('read speed', 'Read Speed - Storage'), ('max cpu height', 'Max CPU Height - Case'), ('form factor', 'Form Factor - Power Supply'), ('cache', 'Cache - CPU'), ('dimensions', 'Dimensions - Power Supply'), ('type', 'Type - Cooler'), ('memory speed', 'Memory Speed - Motherboard'), ('powerConsumption', 'Power Consumption - Motherboard'), ('expansion slots', 'Expansion Slots - Case'), ('write speed', 'Write Speed - Storage'), ('memory type', 'Memory Type - GPU'), ('refresh rate', 'Refresh Rate - Monitor'), ('modularity', 'Modularity - Power Supply'), ('fan', 'Fan - Power Supply'), ('dimensions', 'Dimensions - RAM'), ('warranty', 'Warranty - Power Supply'), ('threads', 'Threads - CPU'), ('capacity', 'Capacity - Storage'), ('dimensions', 'Dimensions - Case'), ('dimensions', 'Dimensions - Cooler'), ('connectivity', 'Connectivity - Monitor'), ('max psu length', 'Max PSU Length - Case'), ('chipset', 'Chipset - Motherboard'), ('eco_mode', 'Eco Mode - Power Supply'), ('socket', 'Socket - CPU'), ('size', 'Size - Monitor'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('powerConsumption', 'Power Consumption - CPU'), ('wifi', 'WiFi - Motherboard'), ('bearing type', 'Bearing Type - Cooler'), ('noise level', 'Noise Level - Cooler'), ('pcie slots', 'PCIe Slots - Motherboard'), ('voltage', 'Voltage - RAM'), ('capacity', 'Capacity - RAM'), ('speed', 'Speed - RAM'), ('length', 'Length - GPU'), ('type', 'Type - Storage'), ('interface', 'Interface - Storage'), ('cores', 'Cores - CPU'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('socket', 'Socket - Motherboard'), ('cuda cores', 'CUDA Cores - GPU'), ('chipset', 'Chipset - GPU'), ('ports', 'Ports - GPU'), ('controller', 'Controller - Storage'), ('wattage', 'Wattage - Power Supply'), ('sata ports', 'SATA Ports - Motherboard'), ('latency', 'Latency - RAM'), ('stream_processors', 'Stream Processors - GPU'), ('rgb', 'RGB - RAM'), ('type', 'Type - Motherboard'), ('fan size', 'Fan Size - Cooler'), ('certifications', 'Certifications - Power Supply'), ('form factor', 'Form Factor - Case'), ('airflow', 'Airflow - Cooler'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('motherboard support', 'Motherboard Support - Case'), ('tdp', 'TDP - CPU'), ('form factor', 'Form Factor - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('memory size', 'Memory Size - GPU'), ('resolution', 'Resolution - Monitor'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('architecture', 'Architecture - CPU'), ('max memory', 'Max Memory - Motherboard'), ('response time', 'Response Time - Monitor'), ('memory interface', 'Memory Interface - GPU'), ('directx support', 'DirectX Support - GPU'), ('cooling support', 'Cooling Support - Case'), ('powerConsumption', 'Power Consumption - Cooler'), ('drive bays', 'Drive Bays - Case'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('memory slots', 'Memory Slots - Motherboard')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
