# Generated by Django 4.2.14 on 2024-07-18 12:30

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0018_alter_contactform_state_alter_product_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('max memory', 'Max Memory - Motherboard'), ('heat spreader', 'Heat Spreader - RAM'), ('controller', 'Controller - Storage'), ('ports', 'Ports - GPU'), ('type', 'Type - Storage'), ('memory slots', 'Memory Slots - Motherboard'), ('dimensions', 'Dimensions - Case'), ('memory size', 'Memory Size - GPU'), ('radiator_size', 'Radiator Size - Cooler'), ('type', 'Type - Cooler'), ('warranty', 'Warranty - Power Supply'), ('powerConsumption', 'Power Consumption - CPU'), ('type', 'Type - Motherboard'), ('connectivity', 'Connectivity - Monitor'), ('drive bays', 'Drive Bays - Case'), ('latency', 'Latency - RAM'), ('read speed', 'Read Speed - Storage'), ('wifi', 'WiFi - Motherboard'), ('length', 'Length - GPU'), ('fan', 'Fan - Power Supply'), ('threads', 'Threads - CPU'), ('interface', 'Interface - Storage'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('lan', 'LAN - Motherboard'), ('max psu length', 'Max PSU Length - Case'), ('memory interface', 'Memory Interface - GPU'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('modules', 'Modules - RAM'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('socket', 'Socket - Motherboard'), ('resolution', 'Resolution - Monitor'), ('expansion slots', 'Expansion Slots - Case'), ('socket', 'Socket - CPU'), ('panel type', 'Panel Type - Monitor'), ('refresh rate', 'Refresh Rate - Monitor'), ('modularity', 'Modularity - Power Supply'), ('cores', 'Cores - CPU'), ('wattage', 'Wattage - Power Supply'), ('support', 'Support - Motherboard'), ('capacity', 'Capacity - RAM'), ('sata ports', 'SATA Ports - Motherboard'), ('pcie slots', 'PCIe Slots - Motherboard'), ('front panel ports', 'Front Panel Ports - Case'), ('chipset', 'Chipset - GPU'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('speed', 'Speed - RAM'), ('certifications', 'Certifications - Power Supply'), ('cuda cores', 'CUDA Cores - GPU'), ('airflow', 'Airflow - Cooler'), ('max gpu length', 'Max GPU Length - Case'), ('form factor', 'Form Factor - Storage'), ('architecture', 'Architecture - CPU'), ('chipset', 'Chipset - CPU'), ('memory type', 'Memory Type - GPU'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('dimensions', 'Dimensions - RAM'), ('dimensions', 'Dimensions - Power Supply'), ('type', 'Type - RAM'), ('fan size', 'Fan Size - Power Supply'), ('fan size', 'Fan Size - Cooler'), ('motherboard support', 'Motherboard Support - Case'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('powerConsumption', 'Power Consumption - Motherboard'), ('powerConsumption', 'Power Consumption - Cooler'), ('dimensions', 'Dimensions - Cooler'), ('size', 'Size - Monitor'), ('form factor', 'Form Factor - Power Supply'), ('max cpu height', 'Max CPU Height - Case'), ('form factor', 'Form Factor - Motherboard'), ('rgb', 'RGB - RAM'), ('bearing type', 'Bearing Type - Cooler'), ('eco_mode', 'Eco Mode - Power Supply'), ('capacity', 'Capacity - Storage'), ('chipset', 'Chipset - Motherboard'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('tdp', 'TDP - CPU'), ('powerConsumption', 'Power Consumption - GPU'), ('stream_processors', 'Stream Processors - GPU'), ('memory speed', 'Memory Speed - Motherboard'), ('write speed', 'Write Speed - Storage'), ('noise level', 'Noise Level - Cooler'), ('voltage', 'Voltage - RAM'), ('rgb', 'RGB - Cooler'), ('form factor', 'Form Factor - Case'), ('directx support', 'DirectX Support - GPU'), ('response time', 'Response Time - Monitor'), ('cache', 'Cache - CPU'), ('cooling support', 'Cooling Support - Case'), ('usb ports', 'USB Ports - Motherboard')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='checkoutinfo',
            name='product',
            field=models.ManyToManyField(to='backendAPI.product'),
        ),
    ]
