# Generated by Django 4.2.14 on 2024-07-19 14:23

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0020_newsletter_alter_product_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='object',
        ),
        migrations.AddField(
            model_name='contactform',
            name='company',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='contactform',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='dateSend',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('solved', 'Résolu'), ('en-attente', 'En Attente')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('type', 'Type - RAM'), ('dimensions', 'Dimensions - RAM'), ('form factor', 'Form Factor - Power Supply'), ('sata ports', 'SATA Ports - Motherboard'), ('socket', 'Socket - CPU'), ('radiator_size', 'Radiator Size - Cooler'), ('pcie slots', 'PCIe Slots - Motherboard'), ('max psu length', 'Max PSU Length - Case'), ('form factor', 'Form Factor - Storage'), ('latency', 'Latency - RAM'), ('warranty', 'Warranty - Power Supply'), ('usb ports', 'USB Ports - Motherboard'), ('powerConsumption', 'Power Consumption - GPU'), ('airflow', 'Airflow - Cooler'), ('memory type', 'Memory Type - GPU'), ('capacity', 'Capacity - RAM'), ('tdp', 'TDP - CPU'), ('refresh rate', 'Refresh Rate - Monitor'), ('socket', 'Socket - Motherboard'), ('cores', 'Cores - CPU'), ('heat spreader', 'Heat Spreader - RAM'), ('stream_processors', 'Stream Processors - GPU'), ('response time', 'Response Time - Monitor'), ('read speed', 'Read Speed - Storage'), ('form factor', 'Form Factor - Case'), ('fan size', 'Fan Size - Cooler'), ('expansion slots', 'Expansion Slots - Case'), ('memory interface', 'Memory Interface - GPU'), ('motherboard support', 'Motherboard Support - Case'), ('directx support', 'DirectX Support - GPU'), ('memory slots', 'Memory Slots - Motherboard'), ('noise level', 'Noise Level - Cooler'), ('voltage', 'Voltage - RAM'), ('rgb', 'RGB - RAM'), ('form factor', 'Form Factor - Motherboard'), ('size', 'Size - Monitor'), ('powerConsumption', 'Power Consumption - CPU'), ('architecture', 'Architecture - CPU'), ('write speed', 'Write Speed - Storage'), ('cuda cores', 'CUDA Cores - GPU'), ('eco_mode', 'Eco Mode - Power Supply'), ('capacity', 'Capacity - Storage'), ('panel type', 'Panel Type - Monitor'), ('chipset', 'Chipset - GPU'), ('length', 'Length - GPU'), ('support', 'Support - Motherboard'), ('controller', 'Controller - Storage'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('dimensions', 'Dimensions - Power Supply'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('connectivity', 'Connectivity - Monitor'), ('rgb', 'RGB - Cooler'), ('type', 'Type - Cooler'), ('powerConsumption', 'Power Consumption - Motherboard'), ('memory speed', 'Memory Speed - Motherboard'), ('cache', 'Cache - CPU'), ('chipset', 'Chipset - Motherboard'), ('wifi', 'WiFi - Motherboard'), ('threads', 'Threads - CPU'), ('wattage', 'Wattage - Power Supply'), ('memory size', 'Memory Size - GPU'), ('chipset', 'Chipset - CPU'), ('fan', 'Fan - Power Supply'), ('ports', 'Ports - GPU'), ('lan', 'LAN - Motherboard'), ('modularity', 'Modularity - Power Supply'), ('interface', 'Interface - Storage'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('bearing type', 'Bearing Type - Cooler'), ('fan size', 'Fan Size - Power Supply'), ('dimensions', 'Dimensions - Cooler'), ('dimensions', 'Dimensions - Case'), ('certifications', 'Certifications - Power Supply'), ('type', 'Type - Motherboard'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('front panel ports', 'Front Panel Ports - Case'), ('modules', 'Modules - RAM'), ('speed', 'Speed - RAM'), ('max cpu height', 'Max CPU Height - Case'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('powerConsumption', 'Power Consumption - Cooler'), ('type', 'Type - Storage'), ('max gpu length', 'Max GPU Length - Case'), ('max memory', 'Max Memory - Motherboard'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('drive bays', 'Drive Bays - Case'), ('cooling support', 'Cooling Support - Case'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('resolution', 'Resolution - Monitor')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
