# Generated by Django 4.2.14 on 2024-07-19 14:26

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0022_alter_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('cores', 'Cores - CPU'), ('modularity', 'Modularity - Power Supply'), ('speed', 'Speed - RAM'), ('powerConsumption', 'Power Consumption - CPU'), ('dimensions', 'Dimensions - Cooler'), ('wifi', 'WiFi - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('size', 'Size - Monitor'), ('memory interface', 'Memory Interface - GPU'), ('architecture', 'Architecture - CPU'), ('sata ports', 'SATA Ports - Motherboard'), ('fan size', 'Fan Size - Cooler'), ('socket', 'Socket - Motherboard'), ('stream_processors', 'Stream Processors - GPU'), ('max psu length', 'Max PSU Length - Case'), ('noise level', 'Noise Level - Cooler'), ('form factor', 'Form Factor - Motherboard'), ('memory size', 'Memory Size - GPU'), ('heat spreader', 'Heat Spreader - RAM'), ('rgb', 'RGB - Cooler'), ('length', 'Length - GPU'), ('powerConsumption', 'Power Consumption - GPU'), ('form factor', 'Form Factor - Power Supply'), ('chipset', 'Chipset - Motherboard'), ('airflow', 'Airflow - Cooler'), ('max memory', 'Max Memory - Motherboard'), ('tdp', 'TDP - CPU'), ('response time', 'Response Time - Monitor'), ('capacity', 'Capacity - RAM'), ('interface', 'Interface - Storage'), ('form factor', 'Form Factor - Storage'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('chipset', 'Chipset - GPU'), ('type', 'Type - Cooler'), ('chipset', 'Chipset - CPU'), ('wattage', 'Wattage - Power Supply'), ('dimensions', 'Dimensions - RAM'), ('front panel ports', 'Front Panel Ports - Case'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('socket', 'Socket - CPU'), ('directx support', 'DirectX Support - GPU'), ('certifications', 'Certifications - Power Supply'), ('dimensions', 'Dimensions - Power Supply'), ('memory type', 'Memory Type - GPU'), ('capacity', 'Capacity - Storage'), ('support', 'Support - Motherboard'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('max cpu height', 'Max CPU Height - Case'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('panel type', 'Panel Type - Monitor'), ('resolution', 'Resolution - Monitor'), ('controller', 'Controller - Storage'), ('ports', 'Ports - GPU'), ('drive bays', 'Drive Bays - Case'), ('type', 'Type - Motherboard'), ('voltage', 'Voltage - RAM'), ('memory slots', 'Memory Slots - Motherboard'), ('modules', 'Modules - RAM'), ('dimensions', 'Dimensions - Case'), ('type', 'Type - Storage'), ('write speed', 'Write Speed - Storage'), ('refresh rate', 'Refresh Rate - Monitor'), ('rgb', 'RGB - RAM'), ('cooling support', 'Cooling Support - Case'), ('pcie slots', 'PCIe Slots - Motherboard'), ('warranty', 'Warranty - Power Supply'), ('cache', 'Cache - CPU'), ('fan', 'Fan - Power Supply'), ('latency', 'Latency - RAM'), ('cuda cores', 'CUDA Cores - GPU'), ('max gpu length', 'Max GPU Length - Case'), ('powerConsumption', 'Power Consumption - Motherboard'), ('type', 'Type - RAM'), ('threads', 'Threads - CPU'), ('expansion slots', 'Expansion Slots - Case'), ('memory speed', 'Memory Speed - Motherboard'), ('read speed', 'Read Speed - Storage'), ('lan', 'LAN - Motherboard'), ('connectivity', 'Connectivity - Monitor'), ('form factor', 'Form Factor - Case'), ('eco_mode', 'Eco Mode - Power Supply'), ('radiator_size', 'Radiator Size - Cooler'), ('usb ports', 'USB Ports - Motherboard'), ('powerConsumption', 'Power Consumption - Cooler'), ('bearing type', 'Bearing Type - Cooler'), ('motherboard support', 'Motherboard Support - Case'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('memory bandwidth', 'Memory Bandwidth - GPU')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
