# Generated by Django 4.2.14 on 2024-07-19 14:28

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0023_alter_contactform_company_alter_contactform_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('en-attente', 'En Attente'), ('solved', 'Résolu')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('dimensions', 'Dimensions - Power Supply'), ('write speed', 'Write Speed - Storage'), ('architecture', 'Architecture - CPU'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('max memory', 'Max Memory - Motherboard'), ('socket', 'Socket - Motherboard'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('stream_processors', 'Stream Processors - GPU'), ('read speed', 'Read Speed - Storage'), ('powerConsumption', 'Power Consumption - Motherboard'), ('max gpu length', 'Max GPU Length - Case'), ('memory slots', 'Memory Slots - Motherboard'), ('length', 'Length - GPU'), ('memory size', 'Memory Size - GPU'), ('fan', 'Fan - Power Supply'), ('response time', 'Response Time - Monitor'), ('form factor', 'Form Factor - Case'), ('powerConsumption', 'Power Consumption - GPU'), ('expansion slots', 'Expansion Slots - Case'), ('form factor', 'Form Factor - Power Supply'), ('chipset', 'Chipset - GPU'), ('type', 'Type - Storage'), ('memory type', 'Memory Type - GPU'), ('heat spreader', 'Heat Spreader - RAM'), ('type', 'Type - Motherboard'), ('modularity', 'Modularity - Power Supply'), ('socket', 'Socket - CPU'), ('modules', 'Modules - RAM'), ('memory speed', 'Memory Speed - Motherboard'), ('cuda cores', 'CUDA Cores - GPU'), ('radiator_size', 'Radiator Size - Cooler'), ('resolution', 'Resolution - Monitor'), ('powerConsumption', 'Power Consumption - Cooler'), ('controller', 'Controller - Storage'), ('max cpu height', 'Max CPU Height - Case'), ('lan', 'LAN - Motherboard'), ('pcie slots', 'PCIe Slots - Motherboard'), ('bearing type', 'Bearing Type - Cooler'), ('type', 'Type - Cooler'), ('capacity', 'Capacity - RAM'), ('rgb', 'RGB - RAM'), ('warranty', 'Warranty - Power Supply'), ('rgb', 'RGB - Cooler'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('drive bays', 'Drive Bays - Case'), ('fan size', 'Fan Size - Power Supply'), ('noise level', 'Noise Level - Cooler'), ('dimensions', 'Dimensions - Cooler'), ('connectivity', 'Connectivity - Monitor'), ('form factor', 'Form Factor - Motherboard'), ('ports', 'Ports - GPU'), ('motherboard support', 'Motherboard Support - Case'), ('capacity', 'Capacity - Storage'), ('cache', 'Cache - CPU'), ('wifi', 'WiFi - Motherboard'), ('chipset', 'Chipset - Motherboard'), ('cooling support', 'Cooling Support - Case'), ('speed', 'Speed - RAM'), ('size', 'Size - Monitor'), ('latency', 'Latency - RAM'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('airflow', 'Airflow - Cooler'), ('max psu length', 'Max PSU Length - Case'), ('cores', 'Cores - CPU'), ('type', 'Type - RAM'), ('dimensions', 'Dimensions - RAM'), ('usb ports', 'USB Ports - Motherboard'), ('front panel ports', 'Front Panel Ports - Case'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('powerConsumption', 'Power Consumption - CPU'), ('wattage', 'Wattage - Power Supply'), ('chipset', 'Chipset - CPU'), ('panel type', 'Panel Type - Monitor'), ('directx support', 'DirectX Support - GPU'), ('certifications', 'Certifications - Power Supply'), ('eco_mode', 'Eco Mode - Power Supply'), ('support', 'Support - Motherboard'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('refresh rate', 'Refresh Rate - Monitor'), ('threads', 'Threads - CPU'), ('form factor', 'Form Factor - Storage'), ('memory interface', 'Memory Interface - GPU'), ('voltage', 'Voltage - RAM'), ('dimensions', 'Dimensions - Case'), ('interface', 'Interface - Storage'), ('fan size', 'Fan Size - Cooler'), ('sata ports', 'SATA Ports - Motherboard'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('tdp', 'TDP - CPU')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
