# Generated by Django 4.2.14 on 2024-07-19 14:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0027_alter_product_filters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='dateSend',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('dimensions', 'Dimensions - Case'), ('type', 'Type - Cooler'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('speed', 'Speed - RAM'), ('length', 'Length - GPU'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('eco_mode', 'Eco Mode - Power Supply'), ('rgb', 'RGB - Cooler'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('bearing type', 'Bearing Type - Cooler'), ('size', 'Size - Monitor'), ('radiator_size', 'Radiator Size - Cooler'), ('noise level', 'Noise Level - Cooler'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('airflow', 'Airflow - Cooler'), ('modularity', 'Modularity - Power Supply'), ('warranty', 'Warranty - Power Supply'), ('cores', 'Cores - CPU'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('refresh rate', 'Refresh Rate - Monitor'), ('ports', 'Ports - GPU'), ('rgb', 'RGB - RAM'), ('memory size', 'Memory Size - GPU'), ('usb ports', 'USB Ports - Motherboard'), ('memory speed', 'Memory Speed - Motherboard'), ('latency', 'Latency - RAM'), ('fan size', 'Fan Size - Cooler'), ('support', 'Support - Motherboard'), ('response time', 'Response Time - Monitor'), ('dimensions', 'Dimensions - Cooler'), ('powerConsumption', 'Power Consumption - Motherboard'), ('capacity', 'Capacity - Storage'), ('dimensions', 'Dimensions - RAM'), ('chipset', 'Chipset - GPU'), ('connectivity', 'Connectivity - Monitor'), ('max gpu length', 'Max GPU Length - Case'), ('socket', 'Socket - CPU'), ('lan', 'LAN - Motherboard'), ('chipset', 'Chipset - CPU'), ('tdp', 'TDP - CPU'), ('voltage', 'Voltage - RAM'), ('panel type', 'Panel Type - Monitor'), ('max psu length', 'Max PSU Length - Case'), ('form factor', 'Form Factor - Storage'), ('front panel ports', 'Front Panel Ports - Case'), ('fan size', 'Fan Size - Power Supply'), ('write speed', 'Write Speed - Storage'), ('directx support', 'DirectX Support - GPU'), ('cache', 'Cache - CPU'), ('powerConsumption', 'Power Consumption - CPU'), ('certifications', 'Certifications - Power Supply'), ('chipset', 'Chipset - Motherboard'), ('form factor', 'Form Factor - Power Supply'), ('max cpu height', 'Max CPU Height - Case'), ('cuda cores', 'CUDA Cores - GPU'), ('architecture', 'Architecture - CPU'), ('type', 'Type - Storage'), ('memory type', 'Memory Type - GPU'), ('powerConsumption', 'Power Consumption - Cooler'), ('sata ports', 'SATA Ports - Motherboard'), ('expansion slots', 'Expansion Slots - Case'), ('type', 'Type - Motherboard'), ('memory interface', 'Memory Interface - GPU'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('max memory', 'Max Memory - Motherboard'), ('stream_processors', 'Stream Processors - GPU'), ('dimensions', 'Dimensions - Power Supply'), ('fan', 'Fan - Power Supply'), ('threads', 'Threads - CPU'), ('form factor', 'Form Factor - Motherboard'), ('memory slots', 'Memory Slots - Motherboard'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('cooling support', 'Cooling Support - Case'), ('read speed', 'Read Speed - Storage'), ('drive bays', 'Drive Bays - Case'), ('socket', 'Socket - Motherboard'), ('modules', 'Modules - RAM'), ('powerConsumption', 'Power Consumption - GPU'), ('wifi', 'WiFi - Motherboard'), ('capacity', 'Capacity - RAM'), ('motherboard support', 'Motherboard Support - Case'), ('form factor', 'Form Factor - Case'), ('controller', 'Controller - Storage'), ('type', 'Type - RAM'), ('wattage', 'Wattage - Power Supply'), ('interface', 'Interface - Storage'), ('resolution', 'Resolution - Monitor'), ('pcie slots', 'PCIe Slots - Motherboard'), ('heat spreader', 'Heat Spreader - RAM')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
