# Generated by Django 4.2.14 on 2024-07-22 09:54

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0047_alter_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('solved', 'Résolu'), ('en-attente', 'En Attente')], default='en-attente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('directx support', 'DirectX Support - GPU'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('pcie slots', 'PCIe Slots - Motherboard'), ('socket', 'Socket - CPU'), ('refresh rate', 'Refresh Rate - Monitor'), ('form factor', 'Form Factor - Case'), ('cuda cores', 'CUDA Cores - GPU'), ('write speed', 'Write Speed - Storage'), ('usb ports', 'USB Ports - Motherboard'), ('max memory', 'Max Memory - Motherboard'), ('expansion slots', 'Expansion Slots - Case'), ('memory slots', 'Memory Slots - Motherboard'), ('dimensions', 'Dimensions - Case'), ('radiator_size', 'Radiator Size - Cooler'), ('fan size', 'Fan Size - Power Supply'), ('interface', 'Interface - Storage'), ('capacity', 'Capacity - Storage'), ('ports', 'Ports - GPU'), ('speed', 'Speed - RAM'), ('dimensions', 'Dimensions - Cooler'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('panel type', 'Panel Type - Monitor'), ('eco_mode', 'Eco Mode - Power Supply'), ('form factor', 'Form Factor - Power Supply'), ('form factor', 'Form Factor - Motherboard'), ('memory size', 'Memory Size - GPU'), ('modularity', 'Modularity - Power Supply'), ('drive bays', 'Drive Bays - Case'), ('powerConsumption', 'Power Consumption - Motherboard'), ('chipset', 'Chipset - CPU'), ('max cpu height', 'Max CPU Height - Case'), ('memory interface', 'Memory Interface - GPU'), ('cache', 'Cache - CPU'), ('resolution', 'Resolution - Monitor'), ('size', 'Size - Monitor'), ('rgb', 'RGB - Cooler'), ('rgb', 'RGB - RAM'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('bearing type', 'Bearing Type - Cooler'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('type', 'Type - Motherboard'), ('form factor', 'Form Factor - Storage'), ('certifications', 'Certifications - Power Supply'), ('stream_processors', 'Stream Processors - GPU'), ('latency', 'Latency - RAM'), ('modules', 'Modules - RAM'), ('wifi', 'WiFi - Motherboard'), ('type', 'Type - Cooler'), ('cooling support', 'Cooling Support - Case'), ('memory speed', 'Memory Speed - Motherboard'), ('motherboard support', 'Motherboard Support - Case'), ('powerConsumption', 'Power Consumption - Cooler'), ('max psu length', 'Max PSU Length - Case'), ('threads', 'Threads - CPU'), ('fan size', 'Fan Size - Cooler'), ('controller', 'Controller - Storage'), ('architecture', 'Architecture - CPU'), ('memory type', 'Memory Type - GPU'), ('socket', 'Socket - Motherboard'), ('tdp', 'TDP - CPU'), ('chipset', 'Chipset - GPU'), ('warranty', 'Warranty - Power Supply'), ('capacity', 'Capacity - RAM'), ('noise level', 'Noise Level - Cooler'), ('powerConsumption', 'Power Consumption - CPU'), ('lan', 'LAN - Motherboard'), ('support', 'Support - Motherboard'), ('powerConsumption', 'Power Consumption - GPU'), ('sata ports', 'SATA Ports - Motherboard'), ('dimensions', 'Dimensions - RAM'), ('read speed', 'Read Speed - Storage'), ('airflow', 'Airflow - Cooler'), ('heat spreader', 'Heat Spreader - RAM'), ('fan', 'Fan - Power Supply'), ('response time', 'Response Time - Monitor'), ('voltage', 'Voltage - RAM'), ('cores', 'Cores - CPU'), ('dimensions', 'Dimensions - Power Supply'), ('connectivity', 'Connectivity - Monitor'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('max gpu length', 'Max GPU Length - Case'), ('type', 'Type - RAM'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('type', 'Type - Storage'), ('length', 'Length - GPU'), ('chipset', 'Chipset - Motherboard'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('front panel ports', 'Front Panel Ports - Case'), ('wattage', 'Wattage - Power Supply')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
