# Generated by Django 4.2.14 on 2024-07-22 13:26

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0050_alter_contactform_state_alter_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='phone_num',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('write speed', 'Write Speed - Storage'), ('wattage', 'Wattage - Power Supply'), ('dimensions', 'Dimensions - Case'), ('memory size', 'Memory Size - GPU'), ('form factor', 'Form Factor - Case'), ('type', 'Type - Storage'), ('socket', 'Socket - CPU'), ('pcie slots', 'PCIe Slots - Motherboard'), ('controller', 'Controller - Storage'), ('response time', 'Response Time - Monitor'), ('usb ports', 'USB Ports - Motherboard'), ('rgb', 'RGB - Cooler'), ('rgb', 'RGB - RAM'), ('memory interface', 'Memory Interface - GPU'), ('wifi', 'WiFi - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('max memory', 'Max Memory - Motherboard'), ('certifications', 'Certifications - Power Supply'), ('radiator_size', 'Radiator Size - Cooler'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('sata ports', 'SATA Ports - Motherboard'), ('airflow', 'Airflow - Cooler'), ('form factor', 'Form Factor - Power Supply'), ('eco_mode', 'Eco Mode - Power Supply'), ('type', 'Type - RAM'), ('size', 'Size - Monitor'), ('support', 'Support - Motherboard'), ('fan', 'Fan - Power Supply'), ('panel type', 'Panel Type - Monitor'), ('motherboard support', 'Motherboard Support - Case'), ('socket', 'Socket - Motherboard'), ('speed', 'Speed - RAM'), ('resolution', 'Resolution - Monitor'), ('latency', 'Latency - RAM'), ('form factor', 'Form Factor - Motherboard'), ('bearing type', 'Bearing Type - Cooler'), ('modularity', 'Modularity - Power Supply'), ('powerConsumption', 'Power Consumption - Cooler'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('heat spreader', 'Heat Spreader - RAM'), ('chipset', 'Chipset - CPU'), ('max cpu height', 'Max CPU Height - Case'), ('memory type', 'Memory Type - GPU'), ('interface', 'Interface - Storage'), ('chipset', 'Chipset - GPU'), ('noise level', 'Noise Level - Cooler'), ('stream_processors', 'Stream Processors - GPU'), ('expansion slots', 'Expansion Slots - Case'), ('powerConsumption', 'Power Consumption - Motherboard'), ('type', 'Type - Motherboard'), ('length', 'Length - GPU'), ('drive bays', 'Drive Bays - Case'), ('powerConsumption', 'Power Consumption - CPU'), ('architecture', 'Architecture - CPU'), ('cuda cores', 'CUDA Cores - GPU'), ('cache', 'Cache - CPU'), ('lan', 'LAN - Motherboard'), ('cores', 'Cores - CPU'), ('read speed', 'Read Speed - Storage'), ('chipset', 'Chipset - Motherboard'), ('capacity', 'Capacity - Storage'), ('max psu length', 'Max PSU Length - Case'), ('connectivity', 'Connectivity - Monitor'), ('powerConsumption', 'Power Consumption - GPU'), ('tdp', 'TDP - CPU'), ('modules', 'Modules - RAM'), ('dimensions', 'Dimensions - RAM'), ('dimensions', 'Dimensions - Cooler'), ('form factor', 'Form Factor - Storage'), ('cooling support', 'Cooling Support - Case'), ('max gpu length', 'Max GPU Length - Case'), ('memory speed', 'Memory Speed - Motherboard'), ('front panel ports', 'Front Panel Ports - Case'), ('warranty', 'Warranty - Power Supply'), ('directx support', 'DirectX Support - GPU'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('type', 'Type - Cooler'), ('refresh rate', 'Refresh Rate - Monitor'), ('memory slots', 'Memory Slots - Motherboard'), ('fan size', 'Fan Size - Cooler'), ('threads', 'Threads - CPU'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('dimensions', 'Dimensions - Power Supply'), ('voltage', 'Voltage - RAM'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('ports', 'Ports - GPU'), ('capacity', 'Capacity - RAM')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
