# Generated by Django 4.2.14 on 2024-07-23 13:45

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0057_product_t_specs_alter_contactform_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tech_specs',
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('modules', 'Modules - RAM'), ('sata ports', 'SATA Ports - Motherboard'), ('cache', 'Cache - CPU'), ('dimensions', 'Dimensions - Power Supply'), ('bearing type', 'Bearing Type - Cooler'), ('max psu length', 'Max PSU Length - Case'), ('socket', 'Socket - Motherboard'), ('memory type', 'Memory Type - GPU'), ('tdp', 'TDP - CPU'), ('architecture', 'Architecture - CPU'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('latency', 'Latency - RAM'), ('dimensions', 'Dimensions - RAM'), ('socket', 'Socket - CPU'), ('powerConsumption', 'Power Consumption - Cooler'), ('max cpu height', 'Max CPU Height - Case'), ('drive bays', 'Drive Bays - Case'), ('lan', 'LAN - Motherboard'), ('response time', 'Response Time - Monitor'), ('warranty', 'Warranty - Power Supply'), ('directx support', 'DirectX Support - GPU'), ('form factor', 'Form Factor - Storage'), ('memory slots', 'Memory Slots - Motherboard'), ('support', 'Support - Motherboard'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('memory size', 'Memory Size - GPU'), ('refresh rate', 'Refresh Rate - Monitor'), ('powerConsumption', 'Power Consumption - CPU'), ('eco_mode', 'Eco Mode - Power Supply'), ('capacity', 'Capacity - Storage'), ('modularity', 'Modularity - Power Supply'), ('memory interface', 'Memory Interface - GPU'), ('size', 'Size - Monitor'), ('capacity', 'Capacity - RAM'), ('memory speed', 'Memory Speed - Motherboard'), ('noise level', 'Noise Level - Cooler'), ('write speed', 'Write Speed - Storage'), ('panel type', 'Panel Type - Monitor'), ('controller', 'Controller - Storage'), ('pcie slots', 'PCIe Slots - Motherboard'), ('wifi', 'WiFi - Motherboard'), ('powerConsumption', 'Power Consumption - GPU'), ('form factor', 'Form Factor - Motherboard'), ('cores', 'Cores - CPU'), ('length', 'Length - GPU'), ('form factor', 'Form Factor - Power Supply'), ('type', 'Type - Storage'), ('fan', 'Fan - Power Supply'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('speed', 'Speed - RAM'), ('max gpu length', 'Max GPU Length - Case'), ('voltage', 'Voltage - RAM'), ('dimensions', 'Dimensions - Cooler'), ('chipset', 'Chipset - CPU'), ('type', 'Type - Cooler'), ('dimensions', 'Dimensions - Case'), ('radiator_size', 'Radiator Size - Cooler'), ('chipset', 'Chipset - GPU'), ('fan size', 'Fan Size - Cooler'), ('rgb', 'RGB - Cooler'), ('cuda cores', 'CUDA Cores - GPU'), ('motherboard support', 'Motherboard Support - Case'), ('threads', 'Threads - CPU'), ('type', 'Type - RAM'), ('cooling support', 'Cooling Support - Case'), ('interface', 'Interface - Storage'), ('stream_processors', 'Stream Processors - GPU'), ('wattage', 'Wattage - Power Supply'), ('rgb', 'RGB - RAM'), ('max memory', 'Max Memory - Motherboard'), ('resolution', 'Resolution - Monitor'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('connectivity', 'Connectivity - Monitor'), ('airflow', 'Airflow - Cooler'), ('usb ports', 'USB Ports - Motherboard'), ('expansion slots', 'Expansion Slots - Case'), ('chipset', 'Chipset - Motherboard'), ('heat spreader', 'Heat Spreader - RAM'), ('front panel ports', 'Front Panel Ports - Case'), ('ports', 'Ports - GPU'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('certifications', 'Certifications - Power Supply'), ('form factor', 'Form Factor - Case'), ('powerConsumption', 'Power Consumption - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('read speed', 'Read Speed - Storage'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('type', 'Type - Motherboard')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
