# Generated by Django 4.2.14 on 2024-07-28 08:45

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0057_alter_product_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='t_specs',
            field=wagtail.fields.StreamField([('TechnicalSpecs', wagtail.blocks.StructBlock([('spec_name', wagtail.blocks.TextBlock(blank=True)), ('spec_value', wagtail.blocks.TextBlock(blank=True))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('form factor', 'Form Factor - Storage'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('memory type', 'Memory Type - GPU'), ('architecture', 'Architecture - CPU'), ('interface', 'Interface - Storage'), ('max psu length', 'Max PSU Length - Case'), ('write speed', 'Write Speed - Storage'), ('type', 'Type - Storage'), ('resolution', 'Resolution - Monitor'), ('warranty', 'Warranty - Power Supply'), ('cuda cores', 'CUDA Cores - GPU'), ('expansion slots', 'Expansion Slots - Case'), ('powerConsumption', 'Power Consumption - CPU'), ('modules', 'Modules - RAM'), ('sata ports', 'SATA Ports - Motherboard'), ('threads', 'Threads - CPU'), ('form factor', 'Form Factor - Case'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('bearing type', 'Bearing Type - Cooler'), ('dimensions', 'Dimensions - Case'), ('usb ports', 'USB Ports - Motherboard'), ('drive bays', 'Drive Bays - Case'), ('motherboard support', 'Motherboard Support - Case'), ('rgb', 'RGB - Cooler'), ('stream_processors', 'Stream Processors - GPU'), ('speed', 'Speed - RAM'), ('max memory', 'Max Memory - Motherboard'), ('chipset', 'Chipset - Motherboard'), ('tdp', 'TDP - CPU'), ('length', 'Length - GPU'), ('latency', 'Latency - RAM'), ('response time', 'Response Time - Monitor'), ('fan size', 'Fan Size - Cooler'), ('controller', 'Controller - Storage'), ('wifi', 'WiFi - Motherboard'), ('dimensions', 'Dimensions - RAM'), ('form factor', 'Form Factor - Power Supply'), ('panel type', 'Panel Type - Monitor'), ('cores', 'Cores - CPU'), ('size', 'Size - Monitor'), ('max gpu length', 'Max GPU Length - Case'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('type', 'Type - Cooler'), ('front panel ports', 'Front Panel Ports - Case'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('memory size', 'Memory Size - GPU'), ('cache', 'Cache - CPU'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('cooling support', 'Cooling Support - Case'), ('chipset', 'Chipset - GPU'), ('radiator_size', 'Radiator Size - Cooler'), ('dimensions', 'Dimensions - Power Supply'), ('modularity', 'Modularity - Power Supply'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('type', 'Type - RAM'), ('dimensions', 'Dimensions - Cooler'), ('ports', 'Ports - GPU'), ('max cpu height', 'Max CPU Height - Case'), ('socket', 'Socket - Motherboard'), ('directx support', 'DirectX Support - GPU'), ('type', 'Type - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('memory speed', 'Memory Speed - Motherboard'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('powerConsumption', 'Power Consumption - Cooler'), ('capacity', 'Capacity - Storage'), ('airflow', 'Airflow - Cooler'), ('support', 'Support - Motherboard'), ('powerConsumption', 'Power Consumption - Motherboard'), ('connectivity', 'Connectivity - Monitor'), ('socket', 'Socket - CPU'), ('memory slots', 'Memory Slots - Motherboard'), ('certifications', 'Certifications - Power Supply'), ('powerConsumption', 'Power Consumption - GPU'), ('read speed', 'Read Speed - Storage'), ('capacity', 'Capacity - RAM'), ('noise level', 'Noise Level - Cooler'), ('fan', 'Fan - Power Supply'), ('refresh rate', 'Refresh Rate - Monitor'), ('memory interface', 'Memory Interface - GPU'), ('wattage', 'Wattage - Power Supply'), ('voltage', 'Voltage - RAM'), ('chipset', 'Chipset - CPU'), ('pcie slots', 'PCIe Slots - Motherboard'), ('heat spreader', 'Heat Spreader - RAM'), ('form factor', 'Form Factor - Motherboard'), ('eco_mode', 'Eco Mode - Power Supply'), ('lan', 'LAN - Motherboard'), ('rgb', 'RGB - RAM')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
