# Generated by Django 4.2.14 on 2024-07-24 08:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0058_remove_product_tech_specs_alter_product_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='product',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('solved', 'Résolu'), ('en-attente', 'En Attente')], default='en-attente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('cuda cores', 'CUDA Cores - GPU'), ('chipset', 'Chipset - GPU'), ('form factor', 'Form Factor - Case'), ('form factor', 'Form Factor - Storage'), ('fan', 'Fan - Power Supply'), ('tdp', 'TDP - CPU'), ('max psu length', 'Max PSU Length - Case'), ('dimensions', 'Dimensions - Case'), ('directx support', 'DirectX Support - GPU'), ('motherboard support', 'Motherboard Support - Case'), ('usb ports', 'USB Ports - Motherboard'), ('architecture', 'Architecture - CPU'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('rgb', 'RGB - RAM'), ('socket', 'Socket - Motherboard'), ('memory interface', 'Memory Interface - GPU'), ('length', 'Length - GPU'), ('memory size', 'Memory Size - GPU'), ('powerConsumption', 'Power Consumption - Motherboard'), ('chipset', 'Chipset - Motherboard'), ('voltage', 'Voltage - RAM'), ('airflow', 'Airflow - Cooler'), ('drive bays', 'Drive Bays - Case'), ('cache', 'Cache - CPU'), ('memory type', 'Memory Type - GPU'), ('ports', 'Ports - GPU'), ('capacity', 'Capacity - Storage'), ('modules', 'Modules - RAM'), ('modularity', 'Modularity - Power Supply'), ('stream_processors', 'Stream Processors - GPU'), ('latency', 'Latency - RAM'), ('fan size', 'Fan Size - Power Supply'), ('write speed', 'Write Speed - Storage'), ('radiator_size', 'Radiator Size - Cooler'), ('type', 'Type - Cooler'), ('capacity', 'Capacity - RAM'), ('type', 'Type - Storage'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('dimensions', 'Dimensions - Cooler'), ('type', 'Type - Motherboard'), ('connectivity', 'Connectivity - Monitor'), ('powerConsumption', 'Power Consumption - Cooler'), ('powerConsumption', 'Power Consumption - GPU'), ('expansion slots', 'Expansion Slots - Case'), ('panel type', 'Panel Type - Monitor'), ('memory speed', 'Memory Speed - Motherboard'), ('resolution', 'Resolution - Monitor'), ('cores', 'Cores - CPU'), ('pcie slots', 'PCIe Slots - Motherboard'), ('socket', 'Socket - CPU'), ('dimensions', 'Dimensions - RAM'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('powerConsumption', 'Power Consumption - CPU'), ('heat spreader', 'Heat Spreader - RAM'), ('type', 'Type - RAM'), ('cooling support', 'Cooling Support - Case'), ('max cpu height', 'Max CPU Height - Case'), ('max gpu length', 'Max GPU Length - Case'), ('fan size', 'Fan Size - Cooler'), ('rgb', 'RGB - Cooler'), ('refresh rate', 'Refresh Rate - Monitor'), ('front panel ports', 'Front Panel Ports - Case'), ('wifi', 'WiFi - Motherboard'), ('eco_mode', 'Eco Mode - Power Supply'), ('form factor', 'Form Factor - Power Supply'), ('max memory', 'Max Memory - Motherboard'), ('chipset', 'Chipset - CPU'), ('interface', 'Interface - Storage'), ('memory slots', 'Memory Slots - Motherboard'), ('dimensions', 'Dimensions - Power Supply'), ('warranty', 'Warranty - Power Supply'), ('form factor', 'Form Factor - Motherboard'), ('read speed', 'Read Speed - Storage'), ('response time', 'Response Time - Monitor'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('support', 'Support - Motherboard'), ('certifications', 'Certifications - Power Supply'), ('wattage', 'Wattage - Power Supply'), ('size', 'Size - Monitor'), ('lan', 'LAN - Motherboard'), ('threads', 'Threads - CPU'), ('noise level', 'Noise Level - Cooler'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('sata ports', 'SATA Ports - Motherboard'), ('controller', 'Controller - Storage'), ('speed', 'Speed - RAM'), ('bearing type', 'Bearing Type - Cooler')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='productsInCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendAPI.checkoutinfo')),
                ('product', models.ManyToManyField(to='backendAPI.product')),
            ],
        ),
    ]
