# Generated by Django 4.2.14 on 2024-07-24 15:30

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0064_alter_contactform_state_alter_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('en-attente', 'En Attente'), ('solved', 'Résolu')], default='en-attente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('panel type', 'Panel Type - Monitor'), ('latency', 'Latency - RAM'), ('powerConsumption', 'Power Consumption - GPU'), ('chipset', 'Chipset - Motherboard'), ('socket', 'Socket - Motherboard'), ('warranty', 'Warranty - Power Supply'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('max cpu height', 'Max CPU Height - Case'), ('dimensions', 'Dimensions - RAM'), ('drive bays', 'Drive Bays - Case'), ('usb ports', 'USB Ports - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('powerConsumption', 'Power Consumption - Cooler'), ('ports', 'Ports - GPU'), ('form factor', 'Form Factor - Case'), ('form factor', 'Form Factor - Storage'), ('memory slots', 'Memory Slots - Motherboard'), ('modules', 'Modules - RAM'), ('cores', 'Cores - CPU'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('wifi', 'WiFi - Motherboard'), ('directx support', 'DirectX Support - GPU'), ('capacity', 'Capacity - Storage'), ('expansion slots', 'Expansion Slots - Case'), ('write speed', 'Write Speed - Storage'), ('read speed', 'Read Speed - Storage'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('max memory', 'Max Memory - Motherboard'), ('chipset', 'Chipset - CPU'), ('connectivity', 'Connectivity - Monitor'), ('front panel ports', 'Front Panel Ports - Case'), ('stream_processors', 'Stream Processors - GPU'), ('response time', 'Response Time - Monitor'), ('architecture', 'Architecture - CPU'), ('wattage', 'Wattage - Power Supply'), ('length', 'Length - GPU'), ('memory size', 'Memory Size - GPU'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('motherboard support', 'Motherboard Support - Case'), ('fan size', 'Fan Size - Cooler'), ('cache', 'Cache - CPU'), ('resolution', 'Resolution - Monitor'), ('modularity', 'Modularity - Power Supply'), ('cuda cores', 'CUDA Cores - GPU'), ('lan', 'LAN - Motherboard'), ('powerConsumption', 'Power Consumption - Motherboard'), ('rgb', 'RGB - RAM'), ('max gpu length', 'Max GPU Length - Case'), ('certifications', 'Certifications - Power Supply'), ('speed', 'Speed - RAM'), ('controller', 'Controller - Storage'), ('interface', 'Interface - Storage'), ('size', 'Size - Monitor'), ('eco_mode', 'Eco Mode - Power Supply'), ('refresh rate', 'Refresh Rate - Monitor'), ('memory interface', 'Memory Interface - GPU'), ('dimensions', 'Dimensions - Power Supply'), ('type', 'Type - Storage'), ('rgb', 'RGB - Cooler'), ('voltage', 'Voltage - RAM'), ('support', 'Support - Motherboard'), ('bearing type', 'Bearing Type - Cooler'), ('max psu length', 'Max PSU Length - Case'), ('cooling support', 'Cooling Support - Case'), ('type', 'Type - RAM'), ('sata ports', 'SATA Ports - Motherboard'), ('memory speed', 'Memory Speed - Motherboard'), ('form factor', 'Form Factor - Power Supply'), ('radiator_size', 'Radiator Size - Cooler'), ('heat spreader', 'Heat Spreader - RAM'), ('fan', 'Fan - Power Supply'), ('pcie slots', 'PCIe Slots - Motherboard'), ('socket', 'Socket - CPU'), ('memory type', 'Memory Type - GPU'), ('chipset', 'Chipset - GPU'), ('dimensions', 'Dimensions - Case'), ('dimensions', 'Dimensions - Cooler'), ('type', 'Type - Motherboard'), ('airflow', 'Airflow - Cooler'), ('powerConsumption', 'Power Consumption - CPU'), ('tdp', 'TDP - CPU'), ('capacity', 'Capacity - RAM'), ('type', 'Type - Cooler'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('noise level', 'Noise Level - Cooler'), ('threads', 'Threads - CPU'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('form factor', 'Form Factor - Motherboard')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
