# Generated by Django 4.2.14 on 2024-07-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0062_alter_product_filters'),
        ('backendAPI', '0067_alter_contactform_state_alter_product_filters_and_more'),
    ]

    operations = [
    ]
