# Generated by Django 4.2.14 on 2024-07-28 10:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('backendAPI', '0068_merge_20240725_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('en-attente', 'En Attente'), ('solved', 'Résolu')], default='en-attente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('radiator_size', 'Radiator Size - Cooler'), ('controller', 'Controller - Storage'), ('cuda cores', 'CUDA Cores - GPU'), ('support', 'Support - Motherboard'), ('noise level', 'Noise Level - Cooler'), ('sata ports', 'SATA Ports - Motherboard'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('dimensions', 'Dimensions - RAM'), ('type', 'Type - RAM'), ('max memory', 'Max Memory - Motherboard'), ('bearing type', 'Bearing Type - Cooler'), ('heat spreader', 'Heat Spreader - RAM'), ('rgb', 'RGB - Cooler'), ('fan', 'Fan - Power Supply'), ('type', 'Type - Storage'), ('eco_mode', 'Eco Mode - Power Supply'), ('memory interface', 'Memory Interface - GPU'), ('cores', 'Cores - CPU'), ('drive bays', 'Drive Bays - Case'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('wattage', 'Wattage - Power Supply'), ('type', 'Type - Motherboard'), ('rgb', 'RGB - RAM'), ('capacity', 'Capacity - Storage'), ('resolution', 'Resolution - Monitor'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('wifi', 'WiFi - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('size', 'Size - Monitor'), ('socket', 'Socket - Motherboard'), ('speed', 'Speed - RAM'), ('type', 'Type - Cooler'), ('response time', 'Response Time - Monitor'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('socket', 'Socket - CPU'), ('dimensions', 'Dimensions - Power Supply'), ('refresh rate', 'Refresh Rate - Monitor'), ('threads', 'Threads - CPU'), ('cache', 'Cache - CPU'), ('modularity', 'Modularity - Power Supply'), ('length', 'Length - GPU'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('powerConsumption', 'Power Consumption - CPU'), ('memory size', 'Memory Size - GPU'), ('max cpu height', 'Max CPU Height - Case'), ('read speed', 'Read Speed - Storage'), ('architecture', 'Architecture - CPU'), ('powerConsumption', 'Power Consumption - Motherboard'), ('powerConsumption', 'Power Consumption - GPU'), ('form factor', 'Form Factor - Motherboard'), ('tdp', 'TDP - CPU'), ('stream_processors', 'Stream Processors - GPU'), ('usb ports', 'USB Ports - Motherboard'), ('max gpu length', 'Max GPU Length - Case'), ('interface', 'Interface - Storage'), ('chipset', 'Chipset - Motherboard'), ('front panel ports', 'Front Panel Ports - Case'), ('warranty', 'Warranty - Power Supply'), ('memory type', 'Memory Type - GPU'), ('form factor', 'Form Factor - Power Supply'), ('memory slots', 'Memory Slots - Motherboard'), ('form factor', 'Form Factor - Case'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('connectivity', 'Connectivity - Monitor'), ('powerConsumption', 'Power Consumption - Cooler'), ('airflow', 'Airflow - Cooler'), ('fan size', 'Fan Size - Cooler'), ('lan', 'LAN - Motherboard'), ('voltage', 'Voltage - RAM'), ('ports', 'Ports - GPU'), ('chipset', 'Chipset - GPU'), ('dimensions', 'Dimensions - Case'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('motherboard support', 'Motherboard Support - Case'), ('modules', 'Modules - RAM'), ('max psu length', 'Max PSU Length - Case'), ('panel type', 'Panel Type - Monitor'), ('cooling support', 'Cooling Support - Case'), ('directx support', 'DirectX Support - GPU'), ('form factor', 'Form Factor - Storage'), ('expansion slots', 'Expansion Slots - Case'), ('capacity', 'Capacity - RAM'), ('dimensions', 'Dimensions - Cooler'), ('latency', 'Latency - RAM'), ('write speed', 'Write Speed - Storage'), ('certifications', 'Certifications - Power Supply'), ('chipset', 'Chipset - CPU'), ('pcie slots', 'PCIe Slots - Motherboard'), ('memory speed', 'Memory Speed - Motherboard')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField(null=True)),
                ('gallery', wagtail.fields.StreamField([('Product_Galery', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))], use_json_field=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
