# Generated by Django 4.2.14 on 2024-07-28 10:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0069_alter_contactform_state_alter_product_filters_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gallery',
            field=wagtail.fields.StreamField([('Event_Galery', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('size', 'Size - Monitor'), ('airflow', 'Airflow - Cooler'), ('form factor', 'Form Factor - Power Supply'), ('powerConsumption', 'Power Consumption - Motherboard'), ('modularity', 'Modularity - Power Supply'), ('fan', 'Fan - Power Supply'), ('type', 'Type - RAM'), ('cores', 'Cores - CPU'), ('ports', 'Ports - GPU'), ('length', 'Length - GPU'), ('wattage', 'Wattage - Power Supply'), ('fan size', 'Fan Size - Power Supply'), ('max memory', 'Max Memory - Motherboard'), ('max gpu length', 'Max GPU Length - Case'), ('interface', 'Interface - Storage'), ('chipset', 'Chipset - GPU'), ('threads', 'Threads - CPU'), ('heat spreader', 'Heat Spreader - RAM'), ('form factor', 'Form Factor - Storage'), ('modules', 'Modules - RAM'), ('dimensions', 'Dimensions - RAM'), ('cooling support', 'Cooling Support - Case'), ('chipset', 'Chipset - CPU'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('form factor', 'Form Factor - Motherboard'), ('type', 'Type - Cooler'), ('panel type', 'Panel Type - Monitor'), ('refresh rate', 'Refresh Rate - Monitor'), ('capacity', 'Capacity - Storage'), ('stream_processors', 'Stream Processors - GPU'), ('powerConsumption', 'Power Consumption - CPU'), ('support', 'Support - Motherboard'), ('resolution', 'Resolution - Monitor'), ('drive bays', 'Drive Bays - Case'), ('powerConsumption', 'Power Consumption - Cooler'), ('cuda cores', 'CUDA Cores - GPU'), ('controller', 'Controller - Storage'), ('motherboard support', 'Motherboard Support - Case'), ('read speed', 'Read Speed - Storage'), ('wifi', 'WiFi - Motherboard'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('front panel ports', 'Front Panel Ports - Case'), ('max cpu height', 'Max CPU Height - Case'), ('sata ports', 'SATA Ports - Motherboard'), ('memory slots', 'Memory Slots - Motherboard'), ('max psu length', 'Max PSU Length - Case'), ('bearing type', 'Bearing Type - Cooler'), ('memory type', 'Memory Type - GPU'), ('connectivity', 'Connectivity - Monitor'), ('architecture', 'Architecture - CPU'), ('lan', 'LAN - Motherboard'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('socket', 'Socket - Motherboard'), ('pcie slots', 'PCIe Slots - Motherboard'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('usb ports', 'USB Ports - Motherboard'), ('memory speed', 'Memory Speed - Motherboard'), ('write speed', 'Write Speed - Storage'), ('eco_mode', 'Eco Mode - Power Supply'), ('dimensions', 'Dimensions - Case'), ('dimensions', 'Dimensions - Power Supply'), ('type', 'Type - Storage'), ('certifications', 'Certifications - Power Supply'), ('radiator_size', 'Radiator Size - Cooler'), ('rgb', 'RGB - RAM'), ('tdp', 'TDP - CPU'), ('latency', 'Latency - RAM'), ('socket', 'Socket - CPU'), ('expansion slots', 'Expansion Slots - Case'), ('fan size', 'Fan Size - Cooler'), ('directx support', 'DirectX Support - GPU'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('warranty', 'Warranty - Power Supply'), ('form factor', 'Form Factor - Case'), ('chipset', 'Chipset - Motherboard'), ('type', 'Type - Motherboard'), ('cache', 'Cache - CPU'), ('rgb', 'RGB - Cooler'), ('capacity', 'Capacity - RAM'), ('speed', 'Speed - RAM'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('voltage', 'Voltage - RAM'), ('powerConsumption', 'Power Consumption - GPU'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('dimensions', 'Dimensions - Cooler'), ('response time', 'Response Time - Monitor'), ('noise level', 'Noise Level - Cooler'), ('memory size', 'Memory Size - GPU'), ('memory interface', 'Memory Interface - GPU')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
