# Generated by Django 4.2.14 on 2024-07-28 13:34

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0071_event_promo_text_alter_contactform_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='adress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('type', 'Type - RAM'), ('fan size', 'Fan Size - Cooler'), ('dimensions', 'Dimensions - RAM'), ('cache', 'Cache - CPU'), ('powerConsumption', 'Power Consumption - Motherboard'), ('rgb', 'RGB - RAM'), ('tdp', 'TDP - CPU'), ('interface', 'Interface - Storage'), ('resolution', 'Resolution - Monitor'), ('capacity', 'Capacity - Storage'), ('rgb', 'RGB - Cooler'), ('modularity', 'Modularity - Power Supply'), ('powerConsumption', 'Power Consumption - CPU'), ('lan', 'LAN - Motherboard'), ('threads', 'Threads - CPU'), ('read speed', 'Read Speed - Storage'), ('voltage', 'Voltage - RAM'), ('eco_mode', 'Eco Mode - Power Supply'), ('max cpu height', 'Max CPU Height - Case'), ('dimensions', 'Dimensions - Cooler'), ('front panel ports', 'Front Panel Ports - Case'), ('heat spreader', 'Heat Spreader - RAM'), ('directx support', 'DirectX Support - GPU'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('controller', 'Controller - Storage'), ('capacity', 'Capacity - RAM'), ('connectivity', 'Connectivity - Monitor'), ('length', 'Length - GPU'), ('cooling support', 'Cooling Support - Case'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('wattage', 'Wattage - Power Supply'), ('dimensions', 'Dimensions - Case'), ('refresh rate', 'Refresh Rate - Monitor'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('response time', 'Response Time - Monitor'), ('max memory', 'Max Memory - Motherboard'), ('form factor', 'Form Factor - Case'), ('motherboard support', 'Motherboard Support - Case'), ('memory interface', 'Memory Interface - GPU'), ('warranty', 'Warranty - Power Supply'), ('ports', 'Ports - GPU'), ('socket', 'Socket - Motherboard'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('certifications', 'Certifications - Power Supply'), ('expansion slots', 'Expansion Slots - Case'), ('chipset', 'Chipset - CPU'), ('type', 'Type - Cooler'), ('panel type', 'Panel Type - Monitor'), ('fan size', 'Fan Size - Power Supply'), ('socket', 'Socket - CPU'), ('form factor', 'Form Factor - Power Supply'), ('noise level', 'Noise Level - Cooler'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('powerConsumption', 'Power Consumption - GPU'), ('bearing type', 'Bearing Type - Cooler'), ('memory slots', 'Memory Slots - Motherboard'), ('pcie slots', 'PCIe Slots - Motherboard'), ('write speed', 'Write Speed - Storage'), ('chipset', 'Chipset - Motherboard'), ('stream_processors', 'Stream Processors - GPU'), ('airflow', 'Airflow - Cooler'), ('size', 'Size - Monitor'), ('support', 'Support - Motherboard'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('radiator_size', 'Radiator Size - Cooler'), ('wifi', 'WiFi - Motherboard'), ('memory type', 'Memory Type - GPU'), ('cores', 'Cores - CPU'), ('memory speed', 'Memory Speed - Motherboard'), ('fan', 'Fan - Power Supply'), ('form factor', 'Form Factor - Storage'), ('dimensions', 'Dimensions - Power Supply'), ('usb ports', 'USB Ports - Motherboard'), ('sata ports', 'SATA Ports - Motherboard'), ('latency', 'Latency - RAM'), ('memory size', 'Memory Size - GPU'), ('max psu length', 'Max PSU Length - Case'), ('max gpu length', 'Max GPU Length - Case'), ('drive bays', 'Drive Bays - Case'), ('type', 'Type - Motherboard'), ('cuda cores', 'CUDA Cores - GPU'), ('chipset', 'Chipset - GPU'), ('modules', 'Modules - RAM'), ('architecture', 'Architecture - CPU'), ('speed', 'Speed - RAM'), ('powerConsumption', 'Power Consumption - Cooler'), ('form factor', 'Form Factor - Motherboard'), ('type', 'Type - Storage')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
