# Generated by Django 4.2.14 on 2024-07-28 13:40

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0072_partners_adress_partners_phone_alter_product_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='partner_link',
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('length', 'Length - GPU'), ('noise level', 'Noise Level - Cooler'), ('eco_mode', 'Eco Mode - Power Supply'), ('powerConsumption', 'Power Consumption - CPU'), ('read speed', 'Read Speed - Storage'), ('certifications', 'Certifications - Power Supply'), ('memory interface', 'Memory Interface - GPU'), ('socket', 'Socket - Motherboard'), ('radiator_size', 'Radiator Size - Cooler'), ('powerConsumption', 'Power Consumption - GPU'), ('latency', 'Latency - RAM'), ('connectivity', 'Connectivity - Monitor'), ('type', 'Type - Storage'), ('memory speed', 'Memory Speed - Motherboard'), ('lan', 'LAN - Motherboard'), ('dimensions', 'Dimensions - Power Supply'), ('wifi', 'WiFi - Motherboard'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('fan', 'Fan - Power Supply'), ('powerConsumption', 'Power Consumption - Motherboard'), ('memory type', 'Memory Type - GPU'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('type', 'Type - Motherboard'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('dimensions', 'Dimensions - Case'), ('panel type', 'Panel Type - Monitor'), ('memory size', 'Memory Size - GPU'), ('chipset', 'Chipset - Motherboard'), ('form factor', 'Form Factor - Power Supply'), ('stream_processors', 'Stream Processors - GPU'), ('rgb', 'RGB - Cooler'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('form factor', 'Form Factor - Motherboard'), ('heat spreader', 'Heat Spreader - RAM'), ('usb ports', 'USB Ports - Motherboard'), ('powerConsumption', 'Power Consumption - Cooler'), ('form factor', 'Form Factor - Storage'), ('support', 'Support - Motherboard'), ('socket', 'Socket - CPU'), ('architecture', 'Architecture - CPU'), ('cuda cores', 'CUDA Cores - GPU'), ('drive bays', 'Drive Bays - Case'), ('type', 'Type - RAM'), ('airflow', 'Airflow - Cooler'), ('max gpu length', 'Max GPU Length - Case'), ('interface', 'Interface - Storage'), ('capacity', 'Capacity - RAM'), ('resolution', 'Resolution - Monitor'), ('memory slots', 'Memory Slots - Motherboard'), ('fan size', 'Fan Size - Cooler'), ('sata ports', 'SATA Ports - Motherboard'), ('max cpu height', 'Max CPU Height - Case'), ('controller', 'Controller - Storage'), ('cores', 'Cores - CPU'), ('cooling support', 'Cooling Support - Case'), ('directx support', 'DirectX Support - GPU'), ('tdp', 'TDP - CPU'), ('bearing type', 'Bearing Type - Cooler'), ('form factor', 'Form Factor - Case'), ('cache', 'Cache - CPU'), ('refresh rate', 'Refresh Rate - Monitor'), ('voltage', 'Voltage - RAM'), ('ports', 'Ports - GPU'), ('chipset', 'Chipset - GPU'), ('modules', 'Modules - RAM'), ('dimensions', 'Dimensions - Cooler'), ('expansion slots', 'Expansion Slots - Case'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('warranty', 'Warranty - Power Supply'), ('speed', 'Speed - RAM'), ('dimensions', 'Dimensions - RAM'), ('type', 'Type - Cooler'), ('write speed', 'Write Speed - Storage'), ('response time', 'Response Time - Monitor'), ('pcie slots', 'PCIe Slots - Motherboard'), ('rgb', 'RGB - RAM'), ('front panel ports', 'Front Panel Ports - Case'), ('max memory', 'Max Memory - Motherboard'), ('size', 'Size - Monitor'), ('wattage', 'Wattage - Power Supply'), ('fan size', 'Fan Size - Power Supply'), ('motherboard support', 'Motherboard Support - Case'), ('max psu length', 'Max PSU Length - Case'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('capacity', 'Capacity - Storage'), ('chipset', 'Chipset - CPU'), ('threads', 'Threads - CPU'), ('modularity', 'Modularity - Power Supply')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
    ]
