# Generated by Django 4.2.14 on 2024-07-25 13:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0078_alter_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('wattage', 'Wattage - Power Supply'), ('dimensions', 'Dimensions - Power Supply'), ('response time', 'Response Time - Monitor'), ('fan size', 'Fan Size - Cooler'), ('wifi', 'WiFi - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('size', 'Size - Monitor'), ('cooling support', 'Cooling Support - Case'), ('memory slots', 'Memory Slots - Motherboard'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('connectivity', 'Connectivity - Monitor'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('form factor', 'Form Factor - Motherboard'), ('length', 'Length - GPU'), ('warranty', 'Warranty - Power Supply'), ('front panel ports', 'Front Panel Ports - Case'), ('dimensions', 'Dimensions - RAM'), ('threads', 'Threads - CPU'), ('powerConsumption', 'Power Consumption - Motherboard'), ('powerConsumption', 'Power Consumption - Cooler'), ('refresh rate', 'Refresh Rate - Monitor'), ('interface', 'Interface - Storage'), ('rgb', 'RGB - RAM'), ('socket', 'Socket - Motherboard'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('chipset', 'Chipset - GPU'), ('capacity', 'Capacity - Storage'), ('heat spreader', 'Heat Spreader - RAM'), ('form factor', 'Form Factor - Power Supply'), ('architecture', 'Architecture - CPU'), ('expansion slots', 'Expansion Slots - Case'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('resolution', 'Resolution - Monitor'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('tdp', 'TDP - CPU'), ('type', 'Type - Storage'), ('max memory', 'Max Memory - Motherboard'), ('powerConsumption', 'Power Consumption - CPU'), ('read speed', 'Read Speed - Storage'), ('type', 'Type - Cooler'), ('type', 'Type - Motherboard'), ('memory type', 'Memory Type - GPU'), ('fan', 'Fan - Power Supply'), ('modularity', 'Modularity - Power Supply'), ('sata ports', 'SATA Ports - Motherboard'), ('dimensions', 'Dimensions - Case'), ('noise level', 'Noise Level - Cooler'), ('rgb', 'RGB - Cooler'), ('memory speed', 'Memory Speed - Motherboard'), ('form factor', 'Form Factor - Storage'), ('pcie slots', 'PCIe Slots - Motherboard'), ('cores', 'Cores - CPU'), ('directx support', 'DirectX Support - GPU'), ('capacity', 'Capacity - RAM'), ('lan', 'LAN - Motherboard'), ('chipset', 'Chipset - Motherboard'), ('max gpu length', 'Max GPU Length - Case'), ('usb ports', 'USB Ports - Motherboard'), ('drive bays', 'Drive Bays - Case'), ('voltage', 'Voltage - RAM'), ('memory size', 'Memory Size - GPU'), ('form factor', 'Form Factor - Case'), ('motherboard support', 'Motherboard Support - Case'), ('modules', 'Modules - RAM'), ('support', 'Support - Motherboard'), ('max cpu height', 'Max CPU Height - Case'), ('chipset', 'Chipset - CPU'), ('ports', 'Ports - GPU'), ('powerConsumption', 'Power Consumption - GPU'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('radiator_size', 'Radiator Size - Cooler'), ('write speed', 'Write Speed - Storage'), ('bearing type', 'Bearing Type - Cooler'), ('eco_mode', 'Eco Mode - Power Supply'), ('dimensions', 'Dimensions - Cooler'), ('stream_processors', 'Stream Processors - GPU'), ('type', 'Type - RAM'), ('airflow', 'Airflow - Cooler'), ('max psu length', 'Max PSU Length - Case'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('speed', 'Speed - RAM'), ('certifications', 'Certifications - Power Supply'), ('memory interface', 'Memory Interface - GPU'), ('socket', 'Socket - CPU'), ('cache', 'Cache - CPU'), ('latency', 'Latency - RAM'), ('cuda cores', 'CUDA Cores - GPU'), ('controller', 'Controller - Storage'), ('panel type', 'Panel Type - Monitor')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='productsincheckout',
            name='checkout',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backendAPI.checkoutinfo'),
        ),
    ]
