# Generated by Django 4.2.14 on 2024-07-25 14:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0080_alter_contactform_state_alter_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='state',
            field=models.CharField(choices=[('solved', 'Résolu'), ('en-attente', 'En Attente')], default='en-attente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=wagtail.fields.StreamField([('filterS', wagtail.blocks.StructBlock([('filter_name', wagtail.blocks.ChoiceBlock(choices=[('form factor', 'Form Factor - Motherboard'), ('rgb', 'RGB - RAM'), ('type', 'Type - RAM'), ('chipset', 'Chipset - Motherboard'), ('wattage', 'Wattage - Power Supply'), ('memory interface', 'Memory Interface - GPU'), ('powerConsumption', 'Power Consumption - CPU'), ('type', 'Type - Storage'), ('max cpu height', 'Max CPU Height - Case'), ('cores', 'Cores - CPU'), ('powerConsumption', 'Power Consumption - Cooler'), ('memory bandwidth', 'Memory Bandwidth - GPU'), ('refresh rate', 'Refresh Rate - Monitor'), ('dimensions', 'Dimensions - Cooler'), ('architecture', 'Architecture - CPU'), ('drive bays', 'Drive Bays - Case'), ('directx support', 'DirectX Support - GPU'), ('memory type', 'Memory Type - GPU'), ('memory slots', 'Memory Slots - Motherboard'), ('powerConsumption', 'Power Consumption - GPU'), ('socket', 'Socket - Motherboard'), ('form factor', 'Form Factor - Case'), ('max gpu length', 'Max GPU Length - Case'), ('connectivity', 'Connectivity - Monitor'), ('dimensions', 'Dimensions - Power Supply'), ('eco_mode', 'Eco Mode - Power Supply'), ('m.2 slots', 'M.2 Slots - Motherboard'), ('ports', 'Ports - GPU'), ('front panel ports', 'Front Panel Ports - Case'), ('resolution', 'Resolution - Monitor'), ('dimensions', 'Dimensions - Case'), ('type', 'Type - Motherboard'), ('cooling support', 'Cooling Support - Case'), ('airflow', 'Airflow - Cooler'), ('threads', 'Threads - CPU'), ('capacity', 'Capacity - Storage'), ('speed', 'Speed - RAM'), ('size', 'Size - Monitor'), ('read speed', 'Read Speed - Storage'), ('voltage', 'Voltage - RAM'), ('modules', 'Modules - RAM'), ('interface', 'Interface - Storage'), ('chipset', 'Chipset - GPU'), ('bearing type', 'Bearing Type - Cooler'), ('memory speed', 'Memory Speed - Motherboard'), ('rgb', 'RGB - Cooler'), ('latency', 'Latency - RAM'), ('heat spreader', 'Heat Spreader - RAM'), ('pcie slots', 'PCIe Slots - Motherboard'), ('usb ports', 'USB Ports - Motherboard'), ('warranty', 'Warranty - Power Supply'), ('expansion slots', 'Expansion Slots - Case'), ('noise level', 'Noise Level - Cooler'), ('max memory', 'Max Memory - Motherboard'), ('radiator_size', 'Radiator Size - Cooler'), ('cuda cores', 'CUDA Cores - GPU'), ('motherboard support', 'Motherboard Support - Case'), ('efficiency rating', 'Efficiency Rating - Power Supply'), ('tdp', 'TDP - CPU'), ('panel type', 'Panel Type - Monitor'), ('zero rpm mode', 'Zero RPM Mode - Power Supply'), ('fan', 'Fan - Power Supply'), ('chipset', 'Chipset - CPU'), ('modularity', 'Modularity - Power Supply'), ('dimensions', 'Dimensions - RAM'), ('powerConsumption', 'Power Consumption - Motherboard'), ('form factor', 'Form Factor - Power Supply'), ('wifi', 'WiFi - Motherboard'), ('memory size', 'Memory Size - GPU'), ('length', 'Length - GPU'), ('certifications', 'Certifications - Power Supply'), ('type', 'Type - Cooler'), ('fluid_dynamic_bearing_fan', 'Fluid Dynamic Bearing Fan - Power Supply'), ('fan size', 'Fan Size - Cooler'), ('aspect ratio', 'Aspect Ratio - Monitor'), ('sata ports', 'SATA Ports - Motherboard'), ('fan size', 'Fan Size - Power Supply'), ('cache', 'Cache - CPU'), ('capacity', 'Capacity - RAM'), ('form factor', 'Form Factor - Storage'), ('support', 'Support - Motherboard'), ('controller', 'Controller - Storage'), ('response time', 'Response Time - Monitor'), ('write speed', 'Write Speed - Storage'), ('socket', 'Socket - CPU'), ('stream_processors', 'Stream Processors - GPU'), ('hybrid_silent_fan_control', 'Hybrid Silent Fan Control - Power Supply'), ('lan', 'LAN - Motherboard'), ('max psu length', 'Max PSU Length - Case')], label='Filter by Category', required=False)), ('value', wagtail.blocks.CharBlock(label='Filter Value'))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='productsincheckout',
            name='checkout',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='backendAPI.checkoutinfo'),
        ),
    ]
